name: imv-kiosk
adopt-info: imv
summary: A kiosk image viewer intended for use with mir-kiosk
description: |
  Image viewer for mir-kiosk based on imv

  Pictures will run as a slideshow. The time per picture can be
  changed via "snap set picviewer-kiosk duration=30", the default
  is 10 seconds per image.

  Imv has support for over 30 different image file formats including
    - Photoshop PSD files
    - Animated GIFS
    - Various RAW formats

  To find out more about imv go to
  https://github.com/eXeC64/imv

  To find out more about the snap package of imv go to
  https://github.com/ogra1/picviewer-kiosk

base: core18
grade: stable
confinement: strict
license: MIT

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el

apps:
  imv:
    command: snap/command-chain/desktop-launch $SNAP/bin/imv.wrapper
    daemon: simple
    restart-condition: always
    extensions: [ gnome-3-28 ]
    plugs:
      - hardware-observe
      - network-bind
      - opengl
      - wayland
  sync:
    command: bin/sync.wrapper # daemon runs as root
    daemon: oneshot
    timer: "10:00-22:00/12" # every hour, on the hour, between 10 and 22h
    plugs: [ network ]

hooks:
  configure:
    plugs: [ network ]

parts:
  imv:
    source: https://github.com/eXeC64/imv.git
    source-depth: 1
    source-tag: v4.1.0
    plugin: make
    override-build: |
      # set version
      VER="$(git tag|tail -1)"
      echo "setting version to $VER"
      snapcraftctl set-version $VER
      # force wayland-only build
      sed -i 's/^WINDOWS=all/WINDOWS=wayland/g' config.mk
      # force single threaded build to make xsltproc not fail
      make -j1
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - asciidoc
      - libfreeimage-dev
      - libglu1-mesa-dev
      - libcmocka-dev
      - librsvg2-dev
      - libwayland-dev
      - xsltproc
    stage-packages:
      - libfreeimage3
      - libgomp1
      - libilmbase12
      - libjxr0
      - libopenexr22
      - libopenjp2-7
      - libraw16
      - libwebpmux3
  b2:
    plugin: python
    python-packages: [ b2 ]
  wrappers:
    source: wrappers/
    plugin: dump
    organize:
      imv.wrapper: bin/imv.wrapper
      sync.wrapper: bin/sync.wrapper
