name: omabox
version: git
summary: Internet-connected digital picture frames for Ubuntu Core on a RPi.
description: |
  A Raspberry Pi with a screen that loops over a local directory with pictures and periodically refreshes these from a Backblaze B2 bucket. New pictures in the bucket will, after a while, automatically show up on the picture frame.

  Install Ubuntu Core on a Raspberry Pi and create a Backblaze B2 bucket with some pictures. Create a new B2 App Key pair with read-only access to the bucket. Install the mir-kiosk snap, needed to run graphical applications. The omaBOX snap is next. Configure the B2 bucket and App Key pair.

    snap install mir-kiosk
    snap install omabox
    snap set omabox b2-application-key-id=123abc b2-application-key=abc123 b2-bucket=abc

  Pictures are show for 10 seconds each, this can be changed via the snap config.

    snap set omabox imv-duration=30

  More settings at https://github.com/cimm/omabox
base: core18
grade: stable
confinement: strict
license: MIT

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: s390x
  - build-on: ppc64el

apps:
  imv:
    command: snap/command-chain/desktop-launch $SNAP/bin/imv-wrapper.py
    daemon: simple
    restart-condition: always
    extensions: [ gnome-3-28 ]
    plugs: [ network-bind, opengl, wayland ]
  download:
    command: usr/bin/python3 $SNAP/bin/download.py
    daemon: oneshot # runs as root
    timer: '00:00-24:00/12' # every 2 hours
    plugs: [ network ]
  upload:
    command: usr/bin/python3 $SNAP/bin/upload.py
    daemon: oneshot
    timer: '00:00-24:00/3' # every 8 hours
    plugs: [ network ]
  brightness:
    command: usr/bin/python3 $SNAP/bin/brightness.py
    daemon: oneshot
    timer: '00:00-24:00/48' # every half hour
    plugs: [ display-control ]

hooks:
  configure:
    plugs: [ network ]

parts:
  imv:
    source: https://github.com/eXeC64/imv.git
    source-depth: 1
    source-tag: v4.1.0
    plugin: make
    override-build: |
      # force wayland-only build
      sed -i 's/^WINDOWS=all/WINDOWS=wayland/g' config.mk
      # force single threaded build to make xsltproc not fail
      make -j1
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - asciidoc
      - libfreeimage-dev
      - libglu1-mesa-dev
      - libcmocka-dev
      - librsvg2-dev
      - libwayland-dev
      - xsltproc
    stage-packages:
      - libfreeimage3
      - libgomp1
      - libilmbase12
      - libjxr0
      - libopenexr22
      - libopenjp2-7
      - libraw16
      - libwebpmux3
  b2:
    plugin: python
    python-packages: [ b2 ]
  scripts:
    source: scripts/
    plugin: dump
    organize:
      brightness.py: bin/brightness.py
      download.py: bin/download.py
      imv-wrapper.py: bin/imv-wrapper.py
      upload.py: bin/upload.py
  upload:
    source: upload/dist
    plugin: dump
    organize:
      index.html: upload/index.html
